export const pratosPrincipais = [
  {
    id: "1",
    nome: "Filé Mignon (Paillard)",
    img: "fileMignon.png",
    descricao: "Filé Mignon acompanha Arroz, fritas e salada.",
    preco: "R$ 48,00",
    tempo: " 30 minutos",
    subsecao: "Carnes Vermelhas",
  },
  {
    id: "2",
    nome: "Contra Filé Grelhado com Salada Russa",
    img: "ContraFiléGrelhado.png",
    descricao: "Contra Filé Grelhado com Arroz e salada russa.",
    preco: "R$ 40,00",
    tempo: "30 minutos",
    subsecao: "Carnes Vermelhas",
  },
  {
    id: "3",
    nome: "Mini Picanha Grelhada",
    img: "MiniPicanhaGrelhada.png",
    descricao: "Acompanaha Arroz, fritas e feijão carioca.",
    preco: "R$ 42,00",
    tempo: "20 minutos",
    subsecao: "Carnes Vermelhas",
  },
  {
    id: "4",
    nome: "Filé de Frango Grelhado com Espaguete",
    img: "FiledeFrangoGrelhadoComEspaguete.png",
    descricao: "Espaguete ao sugo. acompanha queijo ralado.",
    preco: "R$ 35,00",
    tempo: "45 minutos",
    subsecao: "Aves",
  },
  {
    id: "5",
    nome: "Filé de Frango Verão",
    img: "FiledeFrangoVerao.png",
    descricao: "Acompanaha Arroz, fritas e feijão carioca.",
    preco: "R$ 50,00",
    tempo: "45 minutos",
    subsecao: "Aves",
  },
  {
    id: "6",
    nome: "Frango à Milanesa",
    img: "frangoMilanesa.png",
    descricao: "Acompanaha Arroz, fritas e feijão carioca.",
    preco: "R$ 45,00",
    tempo: "45 minutos",
    subsecao: "Aves",
  },
  {
    id: "7",
    nome: "Peixe a dorê",
    img: "peixeDore.jpg",
    descricao: "Acompanaha Arroz, fritas e feijão",
    preco: "R$ 45,00",
    tempo: "20 minutos",
    subsecao: "Peixes",
  },
  {
    id: "8",
    nome: "Peixe Grelhado",
    img: "peixeGrelhado.jpg",
    descricao: "R$ 45,00",
    preco: "Acompanaha Arroz, fritas e feijão",
    tempo: "20 minutos",
    subsecao: "Peixes",
  },
  {
    id: "9",
    nome: "Peixe Ao molho branco",
    img: "peixeMolho.jpg",
    descricao: "Acompanaha Arroz, fritas e feijão",
    preco: "R$ 45,00",
    tempo: "20 minutos",
    subsecao: "Peixes",
  },
  {
    id: "10",
    nome: "Macarão carbonara",
    img: "MacCarbonara.jpg",
    descricao: "Acompanaha Arroz, fritas e feijão",
    preco: "R$ 35,00",
    tempo: "15 minutos",
    subsecao: "Massas",
  },
  {
    id: "11",
    nome: "Nhoqui ao Sugo",
    img: "nhoquiAoSugo.jpg",
    descricao: "Acompanaha Arroz, fritas e feijão",
    preco: "R$ 35,00",
    tempo: "15 minutos",
    subsecao: "Massas",
  },
  {
    id: "12",
    nome: "Espaquete Parisiense",
    img: "espaqueteParisiense.jpg",
    descricao: "Acompanaha Arroz, fritas e feijão",
    preco: "R$ 35,00",
    tempo: "15 minutos",
    subsecao: "Massas",
  },
  {
    id: "13",
    nome: "Risoto ao Fungi",
    img: "RisotoaoFungi.jpg",
    descricao: "Acompanaha fritas",
    preco: "R$ 35,00",
    tempo: "15 minutos",
    subsecao: "Risotos",
  },
  {
    id: "14",
    nome: "Risoto Carbonara",
    img: "risotoCarbonara.jpg",
    descricao: "Acompanaha fritas",
    preco: "R$ 35,00",
    tempo: "15 minutos",
    subsecao: "Risotos",
  },
  {
    id: "15",
    nome: "Risoto de camarão",
    img: "risotodecamarao.jpg",
    descricao: "Acompanaha fritas",
    preco: "R$ 55,00",
    tempo: "20 minutos",
    subsecao: "Risotos",
  },
];

export const bebidas = [{
    id: "16",
    nome: "Água",
    img: "agua.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 5,00",
    tempo: "Na hora",
    subsecao: "Sem Álcool",
  },
  {
    id: "17",
    nome: "Suco",
    img: "suco.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 5,00",
    tempo: "Na hora",
    subsecao: "Sem Álcool",
  },
  {
    id: "18",
    nome: "Refrigerante",
    img: "refrigerante.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 5,00",
    tempo: "Na hora",
    subsecao: "Sem Álcool",
  },
  {
    id: "19",
    nome: "Rose",
    img: "vinhorose.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 35,00",
    tempo: "Na hora",
    subsecao: "Vinhos",
  },
  {
    id: "20",
    nome: "Branco",
    img: "vinhoBranco.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 45,00",
    tempo: "Na hora",
    subsecao: "Vinhos",
  },
  {
    id: "21",
    nome: "Suave",
    img: "suave.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 45,00",
    tempo: "Na hora",
    subsecao: "Vinhos",
  },
  {
    id: "22",
    nome: "Mojito",
    img: "Mojito.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 25,00",
    tempo: "Na hora",
    subsecao: "Drinks",
  },
  {
    id: "23",
    nome: "Cuba Libre",
    img: "cubaLibre.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 25,00",
    tempo: "Na hora",
    subsecao: "Drinks"
  },
  {
    id: "24",
    nome: "Caipirinha",
    img: "caipirinha.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 25,00",
    tempo: "Na hora",
    subsecao: "Drinks"
  },
  {
    id: "25",
    nome: "Brahma",
    img: "brahma.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 15,00",
    tempo: "Na hora",
    subsecao: "Cervejas",
  },
  {
    id: "26",
    nome: "Skoll",
    img: "skoll.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 15,00",
    tempo: "Na hora",
    subsecao: "Cervejas",
  },
  {
    id: "27",
    nome: "Bohemia",
    img: "bohemia.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 15,00",
    tempo: "Na hora",
    subsecao: "Cervejas",
  },];

export const sobremesas = [
  {
    id: "28",
    nome: "Sorvete",
    img: "sorvete.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 10,00",
    tempo: " 5 minutos",
  },
  {
    id: "29",
    nome: "Banana Split",
    img: "bananaSplit.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 10,00",
    tempo: " 5 minutos",
  },
  {
    id: "30",
    nome: "Cupcake",
    img: "cupCake.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 10,00",
    tempo: " 5 minutos",
  },
  {
    id: "31",
    nome: "Tiramisu",
    img: "tiramisu.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 10,00",
    tempo: " 5 minutos",
  },
  {
    id: "32",
    nome: "Pudim",
    img: "pudim.jpg",
    descricao: "Neque porro quisquam est qui dolorem ipsum",
    preco: "R$ 10,00",
    tempo: " 5 minutos",
  },
];

export const entradas = [
    {
        id: "33",
        nome: "Cestino di Pane",
        img: "CestinoPaneItaliano.jpg",
        descricao: "Pães Artesanais servidos com Manteiga, Azeite, e pastinhas do dia",
        preco: "R$ 22,00",
        tempo: "Imediato",
      },
      {
        id: "34",
        nome: "Carpaccio á Cipriani",
        img: "carpatio.jpg",
        descricao: "Carpaccio de Carne, servido com lâminas de Cogumelos, lascas de Parmesão e  crema de Balsâmico",
        preco: "R$ 32,00",
        tempo: "Imediato",
      },
      {
        id: "35",
        nome: "Caprese di Burrata",
        img: "caprese.jpg",
        descricao: "Queijo mozarela fresco e muito cremoso, servido em cama de Rúcula e Tomates Frescos",
        preco: "R$ 54,00",
        tempo: " 5 minutos",
      },
      {
        id: "36",
        nome: "Polenta fritta e Gorgonzola",
        img: "polenta.jpg",
        descricao: "polenta frita servida com molho de gorgonzola",
        preco: "R$ 22,00",
        tempo: " 15 minutos",
      },
      {
        id: "37",
        nome: "Arancini di Riso e Linguiça",
        img: "arancini.jpg",
        descricao: "Tradicional bolinho da região da Sicília, preparado com Arroz Arbóreo, Açafrão, linguiça Blumenau e Parmesão",
        preco: "R$ 29,00",
        tempo: " 15 minutos",
      },
      
];
export const saladas = [
    {
        id: "38",
        nome: "Salada com hortelã",
        img: "saladacomhortela.jpg",
        descricao: "Salada colorida, atrativa. O toque especial de hortelã garante um sabor único.",
        preco: "R$ 29,00",
        tempo: " 10 minutos",
      },
      {
        id: "39",
        nome: "Salada de rúcula com manga",
        img: "saladademangacomrucula.jpg",
        descricao: "Rúcula  combinanda com outros vegetais, Manga e  temperos",
        preco: "R$ 29,00",
        tempo: " 10 minutos",
      },
      {
        id: "40",
        nome: "Salada mediterrânea",
        img: "Saladamediterranea.jpg",
        descricao: "Feita com grão-de-bico acompanha molho especial",
        preco: "R$ 29,00",
        tempo: " 10 minutos",
      },
      {
        id: "41",
        nome: "Vinagrete de verão",
        img: "vinagretedeverao.jpg",
        descricao: "O vinagrete é uma opção versátil, exelente como acompanhamento de carnes vermelhas.",
        preco: "R$ 29,00",
        tempo: " 10 minutos",
      },
      {
        id: "42",
        nome: "Salada Niçoise",
        img: "saladanicoise.jpg",
        descricao: "Um grande clássico da cozinha francesa, uma opção ideal para ser consumida durante o verão",
        preco: "R$ 29,00",
        tempo: " 10 minutos",
      },    
];
